blog_app/urls.py
from django.urls import path 
from .import views

app_name ="blog_app"

urlpatterns = [
    path('',views.all_articles,name="all_articles"),  # display all projects
    path('article/<slug:slug>',views.article, name="article")
    
]

main_app/urls.py
from django.urls import path 
from .import views

app_name ="main_app"

urlpatterns = [
    path('',views.homePage,name="homePage"), # My landing page
    path('send_email/', views.sendEmail, name="sendEmail"),
    
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("main_app.urls")),
    path("projects/",include("projects_app.urls")),
    path("blog/",include("blog_app.urls")),
]
urlpatterns  += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

projects_app/urls.py
from django.urls import path 
from .import views

app_name ="projects_app"

urlpatterns = [
    path('',views.all_projects,name="all_projects"),  # display all projects
    
]

blog_app/models.py
from django.db import models
from django_quill.fields import QuillField
from django.urls import reverse

from io import BytesIO
from PIL import Image
from django.core.files import File
# Create your models here.



class Tag(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name

class Article(models.Model):
    title = models.CharField(max_length=80)
    subtitle = models.CharField(max_length=500)
    thumbnail = models.ImageField(upload_to="blog")
    body = QuillField()
    date_posted = models.DateTimeField(auto_now_add=True)
    featured_article = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, null=True, blank=True)
    slug = models.SlugField(null=True)
    ordering = models.IntegerField( unique = True , null= True , blank = True   )    
    date_added = models.DateTimeField(auto_now_add=True, blank=True,null=True)

    
    
    def get_absolute_url(self):
        return reverse("article", kwargs={"slug":self.slug})
    
    def __str__(self): 
        return str(self.title)

main_app/models.py
from django.db import models

# Create your models here.

class Skill(models.Model):
    name = models.CharField(max_length=100)
    thumbnail = models.ImageField(upload_to="skills")
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True, blank=True,null=True)

    def __str__(self):
        return self.name
    
class Texts(models.Model):
    intro_text = models.TextField()
    about_text = models.TextField()
    greetings_text = models.TextField()
    
    def __str__(self):
        return "Website Texts"
    
class Resume(models.Model):
    resume_file = models.FileField(upload_to="resume")
    
    def __str__(self):
        return "my resume"

projects_app/models.py
from django.db import models
from django_quill.fields import QuillField
# Create your models here.


class ProjectTag(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name
    
class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    thumbnail = models.ImageField(upload_to="project")
    tags = models.ManyToManyField(ProjectTag, null=True, blank=True)
    github = models.URLField(null=True , blank=True)
    live = models.URLField(null=True, blank=True)
    featured = models.BooleanField(default=False)

    demoUsername = models.CharField(max_length=250, null= True, blank= True )
    demoPassword = models.CharField(max_length=250, null= True, blank= True)
    ordering = models.IntegerField( unique = True , null= True , blank = True   )    
    date_added = models.DateTimeField(auto_now_add=True, blank=True,null=True)
    
    def __str__(self):
        return str(self.title)

blog_app/views.py
from django.shortcuts import render
from .models import *
from django.core.paginator import Paginator
# Create your views here.

def all_articles(request):
    articles = Article.objects.all()
    paginator = Paginator(articles, 10) 
   
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {"articles": page_obj}
    return render(request , 'blog_app/article_list.html', context)

def article(request , slug):
    article = Article.objects.get(slug=slug)
    
    articles = Article.objects.exclude( slug = slug )
    
    context = {"article":article, "articles":articles }
    
    return render(request , "blog_app/article.html", context)

main_app/views.py
from django.shortcuts import render , redirect

from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.contrib import messages
from django.conf import settings

from projects_app.models import *
from blog_app.models import *
from main_app.models import *
  

# Create your views here.

def homePage(request):
    projects = Project.objects.filter(featured=True).order_by("ordering")
    articles = Article.objects.filter(featured_article = True).order_by("date_added")[0:3:-1]
    skills = Skill.objects.all()
    texts = Texts.objects.all()
    resume = Resume.objects.all()
    
    context = {
        "projects":projects ,
        "articles":articles,
        "skills":skills,
        "texts":texts,
        "resume":resume,
        }
    return render(request,"main_app/index.html",context)

def sendEmail(request):
    previous_url = request.META['HTTP_REFERER']
    if request.method == 'POST':
        if request.POST['name'] != '' and request.POST['email'] != '' and  request.POST['message'] != '' :
            template = render_to_string('main_app/email_template.html',{
                'name': request.POST['name'],
                'email': request.POST['email'],
                'message': request.POST['message'],
            })
            
            
            email = EmailMessage(
                subject = "EMAIL FROM MY PORTFOLIO",
                body= template, 
                from_email= settings.EMAIL_HOST_USER,
                to = ["bharathbr12@gmail.com"],
                reply_to = [request.POST['email']],
            )
        
            email.content_subtype = "html"
            email.fail_silently =False
            email.send()
        else:
            messages.error(request,"Please fill-up all the fields")
            return redirect(previous_url + '#contact' )
            
    return render (request , "main_app/email_sent.html"  )

projects_app/views.py
from django.shortcuts import render
from projects_app.models import *
# Create your views here.

def all_projects(request):
    projects = Project.objects.all().order_by("date_added")[::-1]
    context = {"projects":projects}
    return render(request,"projects_app/projects_list.html" ,context)

blog_app/templates/blog_app/article.html
{% extends 'main_app/base.html'  %}
{% load static %}
{% load read-time %}
{% block content %}

<style>
  pre{
    background-color: rgb(20, 20, 20) !important;
    padding: 1rem !important;
    border-radius: 0rem ;
    color:rgb(203, 203, 203);
    line-height:1rem !important;
    font-size: 0.85rem !important;
  }

  @media screen and (max-width:350px) {
    pre{
      width: 300px !important;

    }
  }

  @media screen and (min-width:351px) {
    pre{
      width: 310px !important;

    }
  }

  @media screen and (min-width:400px) {
    pre{
      width: 340px !important;

    }
  }

  @media screen and (min-width:460px) {
    pre{
      width: 400px !important;

    }
  }


  @media screen and (min-width:510px) {
    pre{
      width: 100% !important;

    }
    
  }

  @media screen and (min-width:992px) {
    pre{
      width: 100% !important;
      overflow-x: hidden;

    }
    pre:hover{
    overflow-x: scroll !important;
  }
  }


 

</style>
    
    <section >
        <br>
      
        <div class=" d-flex justify-content-center ">

            <div class= "d-flex justify-content-center" >
                <div class="col-12 col-md-9">

                    <div class="d-flex" >  
                        <div class="position-relative"  >
                        <img style="height: 50px; width:50px;border-radius:50%;border: gray 2px solid;" src="{% static 'images/profile.jpg' %}"  class="img-flex"  alt="">
                        </div>

                        <div class="col-6">
                            <div class="row">  
                                <h5 style="margin-left: 3px;color:rgb(227, 227, 227);margin-bottom: 2px;">Bharath Bhaskar</h5> 
                            </div>
                    
                            <div class="row">
                                
                                    <div class="col-1">
                                        <a style="color:rgb(137, 174, 255)" href="https://github.com/bharathbhaskr">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="21" height="21" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                                                <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
                                            </svg>
                                        </a>
                                    </div>
                                    <!-- <div class="col-1">
                                        <a style="color:rgb(137, 174, 255)" href="">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="21" height="21" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
                                                <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
                                            </svg>
                                        </a>
                                    </div> -->
                                    <div class="col-1">
                                        <a style="color:rgb(137, 174, 255)" href="https://www.linkedin.com/in/bharathbhaskar99">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="21" height="21" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
                                                <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
                                            </svg>
                                        </a>
                                    </div>
                        
                            </div>
                        </div>

                    </div> 
                        <div class="row">
                            <div class="col"> 
                            <p style="font-size: 0.85rem;color:rgb(206, 206, 206);margin-left: 2px;margin-top: 15px;"> {{article.date_posted|date:" d M Y"}} <span style="font-weight:700;font-size:larger">  &centerdot; </span> {{article.body.html|readtime}}</p> 
                            </div>
                        </div>
                    <h3 style="color:rgb(227, 227, 227)">{{article.title}}</h3>

                    <div  style="border-left: 3px gray solid;"  class="container">
                        <p style="color:rgb(215, 215, 215)">{{article.subtitle}}</p>
                    </div>
                    <div class="d-flex">
                      {% for tag in article.tags.all %}
                      <div >
                        <div  style="background-color: #8b8b8b53 ; border-radius: 8px;">
                          <p class="d-flex justify-content-center" style="padding:5px 8px;font-size: 0.85rem;color: {% cycle '#ffb43c' '#ff8de8' '#9eaeff' '#dc97ff' '#94ffb4' '#b0f5ff' '#ffa8ad' %};">{{tag.name}}</p> 
                        </div>
                      </div> &nbsp;&nbsp;
                    {% endfor %}
                  </div>

                    
                    <div style="margin: 0cm; padding:0cm;" class="thumb-wrapper"  >
                        <img style="width: 100%;" src="{{article.thumbnail.url}}" class="img-fluid" alt="">
                    </div>
  

                    <br>
                    <div class="container" style="font-family:sans-serif;font-size: 1rem;color:rgb(200, 200, 200) !important;">
                        {{article.body.html|safe|linebreaks}}
                    </div>
                </div>
            </div>

        </div>

    

        <br>
        <br>





        <div class="container">
            <h4 id="sections" style="margin-left: 5px;color: white;margin-top: 0cm;margin-bottom: 0cm;"> More Articles </h4>
            <div style="width:100px;overflow:hidden">
              <hr style="color: #ffec42;border: 2px #ffec42 solid ; opacity: 1;margin:5px ">
           
            </div>
      
        </div>
        <br>
        <br>
    <div class="container-fluid blog-container"  >
        <div class="row d-flex justify-content-center">
          {% for article in articles %}
          <div class=" col-12 col-md-10 col-lg-9">
           {% if forloop.counter == 1 %}
           <div class="d-flex" style="border-top:1px  solid rgb(200, 200, 200);border-bottom:1px  solid rgb(200, 200, 200);"> 
            {% else %}
            <div class="d-flex" style="border-bottom:1px  solid rgb(200, 200, 200);">  
            {% endif %}
           
              <div class="blog-img" style="margin: 20px;">
                <img height="150" src="{{article.thumbnail.url}}" alt="">
              </div>
              <div class="">
               <a href="{% url 'blog_app:article' article.slug %}" class="article-link">  <h3 class="blog-title" style="margin-left: 2px;margin-top:10px;color:white">{{article.title}}</h3> </a>
                <p style="margin-left: 2px;margin-right: 20px;margin-bottom: 8px;color:rgb(225, 225, 225); font-size: 1.1rem;" class="blog-subtitle">
                  {{article.subtitle|truncatechars:160}}
                </p>
  
                <div class="d-flex">
                  {% for tag in article.tags.all %}
                  <div class="">
                    <div class="rounded-pill" style="background-color: #17172284 ">
                      <p class="d-flex justify-content-center" style="padding:3px 5px 3px 5px;font-size: 0.85rem;color: {% cycle 'orange' '#FB04C9' '#7C8EE8' '#E6E116' '#C653FF'  '#00D43F' '#009FB8' '#E6E116' %};">{{tag.name}}</p> 
                    </div>
                  </div> &nbsp;&nbsp;
                 {% endfor %}
              </div>
  
                <div class="row">
                  <div class="col"> 
                    <p style="font-size: 0.7rem;color:rgb(206, 206, 206);margin-left: 2px;margin-top: 3px;"> {{article.date_posted|date:" d M Y"}} <span style="font-weight:700;font-size:larger">  &centerdot; </span> {{article.body.html|readtime}}</p> 
                  </div>
                </div>
  
              </div>
            </div>
  
          </div>
          {% endfor %}
      </div>
  
  
      <div class="container" style="margin-top: 30px;">
        <a href="{% url 'blog_app:all_articles' %}" style="color:#141414 !important;background-color:#ffec42 " class="btn btn-warning rounded-pill">See More
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="18" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"/>
        </svg>
      </a>
      </div>
  
    </div>   
   </div>
   
  <br>
  <br>
  


  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js"></script>
  <script>

      hljs.highlightAll();

      hljs.configure({  
          languages: ['python','javascript']
      });
 
      var toolbarOptions = [
          ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
          ['blockquote', 'code-block'],                     // blocks
          [{ 'header': 1 }, { 'header': 2 }],               // custom button values
          [{ 'list': 'ordered' }, { 'list': 'bullet' }],    // lists
          [{ 'script': 'sub' }, { 'script': 'super' }],     // superscript/subscript
          [{ 'indent': '-1' }, { 'indent': '+1' }],         // indent/outdent
          [{ 'direction': 'rtl' }],                         // text direction
          [{ 'size': ['small', false, 'large', 'huge'] }],  // custom dropdown
          [{ 'header': [1, 2, 3, 4, 5, 6, false] }],         // header dropdown
          [{ 'color': [] }, { 'background': ['white'] }],          // dropdown with defaults from theme
          [{ 'font': [] }],
          [{ 'align': [] }],
          ['clean']                                         // remove formatting button
      ];
  var quill = new Quill('#editor-container', {
  modules: {
      syntax: {
          highlight: text => hljs.highlightAuto(text).value,
      },
      toolbar: [['code-block']]
  },
  theme: 'bubble'
});
  </script>
  

   
    </section>




    <footer style="height: 6rem; bottom: 0; position: fixed; width: 100%; margin-top: 2rem; ">
      <div style="width:93%" class="container-fluid">
          <div class="d-flex justify-content-end">
              <a style="color: #292929 !important;" href="{% url 'main_app:homePage' %}">
                <button style="height: 60px;width: 60px;background-color: #fff175;box-shadow: 0 2px 6px rgb(28, 40, 37);" class="btn rounded-circle" >
                  <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-house-door" viewBox="0 0 16 16">
                    <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146ZM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5Z"/>
                  </svg>
                </button>
              </a>
          </div>
      </div>
  </footer>
  
    

{% endblock content %}

blog_app/templates/blog_app/article_list.html
{% extends 'main_app/base.html' %}
{% load static %}

{% load read-time %}

{% block content %}
 
<section class="py-5" id="blog" >
  <div class="container">
    <h2 id="sections" style="margin-left: 5px;color: white;margin-top: 0cm;margin-bottom: 0cm;">My Blog </h2>
    <div style="width:100px;overflow:hidden">
      <hr style="color: #ffec42;border: 2px #ffec42 solid ; opacity: 1;margin:5px ">

    </div>


    <p style="margin-left: 5px;color:rgb(215, 215, 215);margin-top: 0cm;margin-bottom: 3px;font-size:1.1rem;"> Some
      articles from my tech blog </p>

  </div>

  <br><br>


  <div class="container-fluid blog-container">
    <div class="row d-flex justify-content-center">
      {% for article in articles %}
      <div class=" col-12 col-md-10 col-lg-9">
        {% if forloop.counter == 1 %}
        <div class="d-flex"
          style="border-top:1px  solid rgba(200, 200, 200, 0.126);border-bottom:1px  solid rgba(200, 200, 200, 0.126);">
          {% else %}
          <div class="d-flex" style="border-bottom:1px  solid rgba(200, 200, 200, 0.126);">
            {% endif %}

            <div class="blog-img" style="margin: 20px;">
              <img height="150" src="{{article.thumbnail.url}}" alt="">
            </div>
            <div class="">
              <a href="{% url 'blog_app:article' article.slug %}" class="article-link">
                <h3 class="blog-title" style="margin-left: 2px;margin-top:10px;color:white">{{article.title}}</h3>
              </a>
              <p style="margin-left: 2px;margin-right: 20px;margin-bottom: 8px;color:rgb(225, 225, 225); font-size: 1.1rem;"
                class="blog-subtitle">
                {{article.subtitle|truncatechars:160}}
              </p>


                <div class="d-flex">
                  {% for tag in article.tags.all %}
                  <div >
                    <div  style="background-color: #8b8b8b53 ; border-radius: 8px;">
                      <p class="d-flex justify-content-center" style="padding:5px 8px;font-size: 0.85rem;color: {% cycle '#ffb43c' '#ff8de8' '#9eaeff' '#dc97ff' '#94ffb4' '#b0f5ff' '#ffa8ad' %};">{{tag.name}}</p> 
                    </div>
                  </div> &nbsp;&nbsp;
                {% endfor %}
              </div>

              <div class="row">
                <div class="col">
                  <p style="font-size: 0.7rem;color:rgb(206, 206, 206);margin-left: 2px;margin-top: 3px;">
                    {{article.date_posted|date:" d M Y"}} <span style="font-weight:700;font-size:larger"> &centerdot;
                    </span> {{article.body.html|readtime}}</p>
                </div>
              </div>

            </div>
          </div>

        </div>
        {% endfor %}
      </div>


    

    </div>
  </div>




</section>

<footer style="height: 6rem; bottom: 0; position: fixed; width: 100%; margin-top: 2rem; ">
  <div style="width:93%" class="container-fluid">
      <div class="d-flex justify-content-end">
          <a style="color: #292929 !important;" href="{% url 'main_app:homePage' %}">
            <button style="height: 60px;width: 60px;background-color: #fff175;box-shadow: 0 2px 6px rgb(28, 40, 37);" class="btn rounded-circle" >
              <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-house-door" viewBox="0 0 16 16">
                <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146ZM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5Z"/>
              </svg>
            </button>
          </a>
      </div>
  </div>
</footer>


{% endblock content %}

main_app/templates/main_app/email_sent.html
{% extends 'main_app/base.html' %}

{% block content %}

<style type="text/css">
	html, body{
		height: 100%;
	}

	#page-wrapper{
		height: 100%;
		display: flex;
		justify-content: center;
		align-items: center;
		text-align: center;
		background-color: #0c0c14;
	}

	#success-box{
		max-width: 800px;
		height: auto;
		background-color: rgba(78, 78, 78, 0.124);
		border:1px solid #ffc200;
		border-radius: 5px;
		padding: 15px;
		color: rgb(214, 214, 214);
	}

	#success-box p{
		font-size: 18px;
	}

</style>

<div id="page-wrapper">
	<div id="success-box" class="content-block">
		<h1>Thanks for reaching out!</h1>
		<p>Your email was successfully sent. Meanwhile please follow me on social media platforms :)</p>
		<a id="back-btn" class="btn btn-success" href="{% url 'main_app:homePage' %}">BACK TO HOME PAGE</a>
	</div>
</div>

{% endblock content %}

main_app/templates/main_app/email_template.html
<p> {{message}}  </p> 

<hr>

 <div>
  <h5>Email From : <span>  <b>  {{name}} </b></span></h5> 
  <h5> Email:  <span> <strong> {{email}} </strong></span></h5>
 </div> 